import { test } from 'node:test';
import assert from 'node:assert/strict';
import { LifecycleObserver, type LifecycleObserverDependencies } from './observer.js';
import type { LifecycleObserverRepository, LifecycleSupervision } from './observer-repository.js';
import { roundTrip } from './round-trip-test-fixture.js';
import type { CloseOperation } from './close-types.js';
function setup() {
 const f=roundTrip(); let now=f.context.nowMs; const faults=new Set<string>(); let healthy=false;let writes=0;let refreshes=0;let fingerprint='economic-1';let operation:CloseOperation|null=null;
 let row:LifecycleSupervision|null={proposalId:42,accountId:'DU_TEST',originalHash:f.evidence.lifecycle.clientOrderHash!,instrumentId:'test',conid:'123',status:'UNAVAILABLE',terminalProof:null,terminalFingerprint:null,automaticRequestId:null,automaticLimitPrice:null,automaticClaimedAt:null,sessionDate:'2026-09-23',sessionStart:new Date(now-3600000).toISOString(),sessionEnd:new Date(now+3600000).toISOString(),exitDeadline:new Date(now+10000).toISOString(),sessionGeneration:1,marginMinutes:15};
 const state={get row(){return row;},set row(v){row=v;},get operation(){return operation;},set operation(v){operation=v;},get writes(){return writes;},get healthy(){return healthy;},get refreshes(){return refreshes;},set now(v:number){now=v;},get now(){return now;},set fingerprint(v:string){fingerprint=v;},faults};
 const refresh=async()=>{refreshes++;const iso=(delta:number)=>new Date(now+delta).toISOString();f.run.started_at=iso(-1000);f.run.completed_at=iso(-50);f.snapshot.capturedAt=iso(-100);f.coverage.executions.window.to=iso(-200);f.evidence.lifecycle.positionSnapshot!.observedAt=iso(-1500);for(const p of f.evidence.lifecycle.positionSnapshot!.positions)p.observedAt=iso(-1500);};
 const store={overdueProtection:async()=>[] as number[],execution:{getRoundTripEvidence:async()=>f.evidence},withAccountLease:async(_a:string,fn:()=>Promise<unknown>)=>fn(),listCandidates:async()=>[42],get:async()=>row,adopt:async()=>{},validateSession:async()=>row!,fingerprint:async()=>fingerprint,accountFresh:async()=>true,health:async()=>{},claimAutomatic:async(_r:LifecycleSupervision,price:number)=>{if(row!.automaticRequestId)return null;row={...row!,automaticRequestId:'once',automaticLimitPrice:price,automaticClaimedAt:new Date(now).toISOString()};return row;},observe:async(_id:number,status:string,_o:unknown,terminal?:{proof:Record<string,unknown>;fingerprint:string})=>{if(row)row={...row,status,...(terminal?{terminalProof:terminal.proof,terminalFingerprint:terminal.fingerprint}:{})};}};
 const deps:LifecycleObserverDependencies={currentContext:()=>({accountId:'DU_TEST',sessionId:'current'}),context:async()=>({...f.context,accountId:'DU_TEST',clientId:7,generation:1,nowMs:now}),refresh,close:{get:async()=>operation,reconcile:async()=>operation!,request:async()=>{writes++;operation={state:'SUBMITTED',originalProposalId:42,submissionAttemptedAt:new Date(now).toISOString(),cancelAttempts:[],failureReason:null} as unknown as CloseOperation;return operation;}},faults:{recordFault:async input=>{faults.add(`${input.proposalId}:${input.code}`);},resolveScope:async(_a,id,codes)=>{for(const key of faults)if(key.startsWith(`${id}:`)&&!codes.includes(key.split(':')[1] as never))faults.delete(key);}},closePrice:async()=>100,assertManagementAllowed:()=>{},automationEnabled:true,adoptExisting:false,exitBeforeCloseMinutes:15,onHealth:value=>{healthy=value;},logCritical:()=>{},now:()=>now};
 const observer=new LifecycleObserver(store as unknown as LifecycleObserverRepository,deps);
 const makeOwned=()=>{f.snapshot.executions.splice(1);f.evidence.fills.splice(1);f.coverage.executions.count=1;f.snapshot.positions.push({accountId:'DU_TEST',conId:'123',position:1});f.coverage.positions.count=1;f.evidence.lifecycle.positionSnapshot!.positions.push({accountId:'DU_TEST',sessionId:'current',conid:'123',instrument:'TEST',quantity:1,observedAt:new Date(now-1500).toISOString()});f.snapshot.openOrders=f.evidence.lifecycle.links.slice(1).map((l,i)=>({accountId:'DU_TEST',conId:'123',brokerOrderId:l.broker_order_id!,orderRef:l.order_ref,permId:l.perm_id,clientId:7,status:'Submitted',remaining:1,filled:0,action:'SELL',orderType:i===0?'LMT':'STP',limitPrice:102,stopPrice:99,totalQuantity:1,parentId:'100',ocaGroup:'owned',ocaType:2,tif:'DAY',secType:'STK',currency:'PLN'}));f.coverage.openOrders.count=2;};
 return {f,state,store,deps,observer,makeOwned};
}
test('automatic final flat observation persists immutable proof and changed economics reopens incident',async()=>{const t=setup();await t.observer.triggerNow();assert.equal(t.state.row?.status,'FLAT');assert.ok(t.state.row?.terminalProof);assert.equal(t.state.healthy,true);t.state.fingerprint='correction';await t.observer.triggerNow();assert.equal(t.state.healthy,false);assert.ok(t.state.faults.has('42:HISTORICAL_EVIDENCE_CHANGED'));assert.equal(t.state.writes,0);});
test('terminal proof tolerates a later legitimate position but catches old working identity',async()=>{const t=setup();await t.observer.triggerNow();t.f.snapshot.positions.push({accountId:'DU_TEST',conId:'123',position:1});await t.observer.triggerNow();assert.equal(t.state.healthy,true);t.f.snapshot.openOrders.push({accountId:'DU_TEST',conId:'123',brokerOrderId:'101',orderRef:'test-TP',permId:'1001',clientId:7,status:'Submitted',remaining:1,filled:0,action:'SELL'});await t.observer.triggerNow();assert.equal(t.state.healthy,false);});
test('protected ownership is observed then one deadline request is made and replay only reconciles',async()=>{const t=setup();t.makeOwned();await t.observer.triggerNow();assert.equal(t.state.row?.status,'PROTECTED');assert.equal(t.state.writes,0);t.state.now+=10000;await t.observer.triggerNow();assert.equal(t.state.writes,1);await t.observer.triggerNow();assert.equal(t.state.writes,1);t.state.now+=15000;await t.observer.triggerNow();assert.ok(t.state.faults.has('42:CLOSE_UNFILLED'));assert.equal(t.state.healthy,false);});
test('pending parent has automatic close authority through existing service, never a direct SELL',async()=>{const t=setup();t.makeOwned();t.f.snapshot.positions=[];t.f.coverage.positions.count=0;t.f.evidence.lifecycle.positionSnapshot!.positions=[];t.f.snapshot.executions=[];t.f.evidence.fills=[];t.f.coverage.executions.count=0;t.f.snapshot.openOrders.push({...t.f.snapshot.openOrders[0],brokerOrderId:'100',orderRef:'test-PARENT',permId:'1000',action:'BUY'});t.f.coverage.openOrders.count=3;await t.observer.triggerNow();assert.equal(t.state.row?.status,'PENDING_ENTRY');t.state.now+=10000;await t.observer.triggerNow();assert.equal(t.state.writes,1);});
for(const failure of ['missing_policy','automation_off','master_off','prior_claim','bad_protection','session_failed'] as const)test(`no automatic write on ${failure}`,async()=>{const t=setup();t.makeOwned();t.state.now+=10000;if(failure==='missing_policy')t.state.row=null;if(failure==='automation_off')t.deps.automationEnabled=false;if(failure==='master_off')t.deps.assertManagementAllowed=()=>{throw Error('off');};if(failure==='prior_claim')t.state.row={...t.state.row!,automaticRequestId:'old'};if(failure==='bad_protection')Object.assign(t.f.snapshot.openOrders[0],{ocaType:1});if(failure==='session_failed')t.store.validateSession=async()=>{throw Error('stale');};await t.observer.triggerNow();assert.equal(t.state.writes,0);assert.equal(t.state.healthy,false);assert.ok(t.state.faults.size>0);});
test('watchdog fences entries during a blocked refresh and shutdown never initiates broker writes',async()=>{const t=setup();let finish!:()=>void;t.deps.refresh=()=>new Promise<void>(resolve=>{finish=resolve;});const run=t.observer.triggerNow();await Promise.resolve();t.state.now+=15000;await t.observer.watchdog();assert.equal(t.state.healthy,false);assert.ok(t.state.faults.has('null:BROKER_STATE_STALE'));const stop=t.observer.stop();finish();await Promise.all([run,stop]);assert.equal(t.state.writes,0);await t.observer.triggerNow();assert.equal(t.state.writes,0);});
test('DB failure is local failed health and cannot create automatic action',async()=>{const t=setup();t.makeOwned();t.store.listCandidates=async()=>{throw Error('database unavailable');};await t.observer.triggerNow();assert.equal(t.state.healthy,false);assert.equal(t.state.writes,0);});
test('lost cancellation after protective intent records protection-gap and stays reserved without retry',async()=>{const t=setup();t.makeOwned();t.state.operation={state:'CANCEL_UNKNOWN',cancelAttempts:[{role:'TP'}],failureReason:'lost_ack'} as CloseOperation;await t.observer.triggerNow();await t.observer.triggerNow();assert.ok(t.state.faults.has('42:CANCEL_UNKNOWN'));assert.ok(t.state.faults.has('42:PROTECTION_GAP'));assert.equal(t.state.writes,0);});

test('manual close watchdog escalates durable protective cancel while reconciliation awaits it',async()=>{const t=setup();t.store.overdueProtection=async()=>[42];t.state.now+=15000;await t.observer.watchdog();assert.ok(t.state.faults.has('42:PROTECTION_GAP'));assert.equal(t.state.writes,0);});

test('flat pending commissions stay accounting-pending and later confirmed economics may complete',async()=>{const t=setup();t.f.evidence.fills[0].commission=null;await t.observer.triggerNow();assert.equal(t.state.row?.status,'ACCOUNTING_PENDING');assert.equal(t.state.row?.terminalProof,null);t.f.evidence.fills[0].commission=.5;t.state.fingerprint='fees_arrived';await t.observer.triggerNow();assert.equal(t.state.row?.status,'FLAT');assert.equal(t.state.healthy,true);});
test('economic correction between evidence reads cannot be hidden in a newer terminal fingerprint',async()=>{const t=setup();let n=0;t.store.fingerprint=async()=>++n===1?'before':'after';await t.observer.triggerNow();assert.equal(t.state.row?.terminalProof,null);assert.ok(t.state.faults.has('42:HISTORICAL_EVIDENCE_CHANGED'));});

test('fractional owned fills matching both broker position snapshots never become healthy or auto-close',async()=>{const t=setup();t.makeOwned();t.f.snapshot.executions[0].shares=.5;t.f.snapshot.positions[0].position=.5;t.f.evidence.lifecycle.positionSnapshot!.positions[0].quantity=.5;t.f.evidence.fills[0].shares=.5;t.state.now+=10000;await t.observer.triggerNow();assert.equal(t.state.row?.status,'HOLD');assert.equal(t.state.healthy,false);assert.equal(t.state.writes,0);assert.ok(t.state.faults.has('42:ORPHAN_OWNERSHIP'));});

for(const source of ['broker_execution','broker_order','local_fill','duplicate_first','duplicate_last'] as const)test(`typed active stock evidence cannot hide foreign asset/currency: ${source}`,async()=>{
 const t=setup();t.makeOwned();t.state.now+=10000;
 if(source==='broker_execution')Object.assign(t.f.snapshot.executions[0],{secType:'FUT',currency:'JPY'});
 if(source==='broker_order')Object.assign(t.f.snapshot.openOrders[0],{secType:'FUT',currency:'JPY'});
 if(source==='local_fill')Object.assign(t.f.evidence.fills[0],{sec_type:'STK',sec_type_conflict:true});
 if(source.startsWith('duplicate')){const row={...t.f.snapshot.executions[0],secType:'FUT',currency:'JPY'};if(source==='duplicate_first')t.f.snapshot.executions.unshift(row);else t.f.snapshot.executions.push(row);t.f.coverage.executions.count++;}
 await t.observer.triggerNow();assert.equal(t.state.row?.status,'HOLD');assert.equal(t.state.healthy,false);assert.equal(t.state.writes,0);assert.ok(t.state.faults.has('42:ORPHAN_OWNERSHIP'));
});

test('failed close uncertainty and protection gap remain visible when local accounting is missing',async()=>{const t=setup();t.makeOwned();t.f.evidence.fills=[];t.state.operation={state:'SUBMISSION_UNKNOWN',cancelAttempts:[{role:'SL'}],failureReason:'lost_ack'} as CloseOperation;await t.observer.triggerNow();assert.ok(t.state.faults.has('42:ORPHAN_OWNERSHIP'));assert.ok(t.state.faults.has('42:SUBMISSION_UNKNOWN'));assert.ok(t.state.faults.has('42:PROTECTION_GAP'));assert.equal(t.state.writes,0);});
test('a fill denormalized onto another proposal cannot prove active ownership',async()=>{const t=setup();t.makeOwned();t.f.evidence.fills[0].proposed_order_id=999;t.state.now+=10000;await t.observer.triggerNow();assert.equal(t.state.healthy,false);assert.equal(t.state.writes,0);assert.ok(t.state.faults.has('42:ORPHAN_OWNERSHIP'));});
