-- Unknown historic provenance is deliberately not backfilled.
CREATE TABLE IF NOT EXISTS candles_1m (
  conid TEXT NOT NULL, symbol TEXT NOT NULL, ts TIMESTAMPTZ NOT NULL,
  open DOUBLE PRECISION NOT NULL, high DOUBLE PRECISION NOT NULL,
  low DOUBLE PRECISION NOT NULL, close DOUBLE PRECISION NOT NULL,
  volume DOUBLE PRECISION NOT NULL, PRIMARY KEY (conid, ts)
);
CREATE INDEX IF NOT EXISTS candles_1m_symbol_ts_idx ON candles_1m (symbol, ts DESC);
ALTER TABLE candles_1m ADD COLUMN IF NOT EXISTS source text;
CREATE TABLE IF NOT EXISTS candles_5m (
  conid TEXT NOT NULL, symbol TEXT NOT NULL, ts TIMESTAMPTZ NOT NULL,
  open DOUBLE PRECISION NOT NULL, high DOUBLE PRECISION NOT NULL,
  low DOUBLE PRECISION NOT NULL, close DOUBLE PRECISION NOT NULL,
  volume DOUBLE PRECISION NOT NULL, PRIMARY KEY (conid, ts)
);
CREATE INDEX IF NOT EXISTS candles_5m_symbol_ts_idx ON candles_5m (symbol, ts DESC);
ALTER TABLE candles_5m ADD COLUMN IF NOT EXISTS source text;
CREATE TABLE IF NOT EXISTS candles_1h (
  conid TEXT NOT NULL, symbol TEXT NOT NULL, ts TIMESTAMPTZ NOT NULL,
  open DOUBLE PRECISION NOT NULL, high DOUBLE PRECISION NOT NULL,
  low DOUBLE PRECISION NOT NULL, close DOUBLE PRECISION NOT NULL,
  volume DOUBLE PRECISION NOT NULL, PRIMARY KEY (conid, ts)
);
CREATE INDEX IF NOT EXISTS candles_1h_symbol_ts_idx ON candles_1h (symbol, ts DESC);
ALTER TABLE candles_1h ADD COLUMN IF NOT EXISTS source text;
CREATE TABLE IF NOT EXISTS candles_4h (
  conid TEXT NOT NULL, symbol TEXT NOT NULL, ts TIMESTAMPTZ NOT NULL,
  open DOUBLE PRECISION NOT NULL, high DOUBLE PRECISION NOT NULL,
  low DOUBLE PRECISION NOT NULL, close DOUBLE PRECISION NOT NULL,
  volume DOUBLE PRECISION NOT NULL, PRIMARY KEY (conid, ts)
);
CREATE INDEX IF NOT EXISTS candles_4h_symbol_ts_idx ON candles_4h (symbol, ts DESC);
ALTER TABLE candles_4h ADD COLUMN IF NOT EXISTS source text;
CREATE TABLE IF NOT EXISTS candles_12h (
  conid TEXT NOT NULL, symbol TEXT NOT NULL, ts TIMESTAMPTZ NOT NULL,
  open DOUBLE PRECISION NOT NULL, high DOUBLE PRECISION NOT NULL,
  low DOUBLE PRECISION NOT NULL, close DOUBLE PRECISION NOT NULL,
  volume DOUBLE PRECISION NOT NULL, PRIMARY KEY (conid, ts)
);
CREATE INDEX IF NOT EXISTS candles_12h_symbol_ts_idx ON candles_12h (symbol, ts DESC);
ALTER TABLE candles_12h ADD COLUMN IF NOT EXISTS source text;
CREATE TABLE IF NOT EXISTS candles_1d (
  conid TEXT NOT NULL, symbol TEXT NOT NULL, ts TIMESTAMPTZ NOT NULL,
  open DOUBLE PRECISION NOT NULL, high DOUBLE PRECISION NOT NULL,
  low DOUBLE PRECISION NOT NULL, close DOUBLE PRECISION NOT NULL,
  volume DOUBLE PRECISION NOT NULL, PRIMARY KEY (conid, ts)
);
CREATE INDEX IF NOT EXISTS candles_1d_symbol_ts_idx ON candles_1d (symbol, ts DESC);
ALTER TABLE candles_1d ADD COLUMN IF NOT EXISTS source text;
CREATE TABLE IF NOT EXISTS candles_1w (
  conid TEXT NOT NULL, symbol TEXT NOT NULL, ts TIMESTAMPTZ NOT NULL,
  open DOUBLE PRECISION NOT NULL, high DOUBLE PRECISION NOT NULL,
  low DOUBLE PRECISION NOT NULL, close DOUBLE PRECISION NOT NULL,
  volume DOUBLE PRECISION NOT NULL, PRIMARY KEY (conid, ts)
);
CREATE INDEX IF NOT EXISTS candles_1w_symbol_ts_idx ON candles_1w (symbol, ts DESC);
ALTER TABLE candles_1w ADD COLUMN IF NOT EXISTS source text;
